/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package semesterprojekt;

import java.util.ArrayList;
/**
 *
 * @author Squid
 */
public class GUI extends javax.swing.JPanel 
{
    Overview overview;
    Receipt receipt = new Receipt();
    Basket basket = new Basket();
    Animal animal;

//    Display display;

    /**
     * Creates new form GUI
     */
    public GUI() 
    {
//        ArrayList<Aquatic> aquatic;
//        aquatic = new ArrayList<>();
//        aquatic.add(new Aquatic(1, 3, 50, "Goldfish", 10, true, false, 50, true, 5));
        initComponents();
        paneDisplay1.setnavneAquatic(null);
        paneDisplay2.setnavneReptile(null);
        paneDisplay3.setnavneMammal(null);
        paneDisplay4.setnavneBird(null);
    }
        public int getAntal1(){
            return (Integer) paneDisplay1.getAntal();
        }
        public int getAntal2(){
            return (Integer) paneDisplay2.getAntal();
        }
        public int getAntal3(){
            return (Integer) paneDisplay3.getAntal();
        }
        public int getAntal4(){
            return (Integer) paneDisplay4.getAntal();
        }
        
        public void setTotalPrice(int totPrice)
        {
            receipt1.setTotalPrice(totPrice);
        }
        
        public String getSelectAnimal1(){
            return paneDisplay1.getSelectAnimal();
        }
        public int getSelectIndex1(){
            return paneDisplay1.getSelectedIndex();
        }
        
        public String getSelectAnimal2(){
            return paneDisplay2.getSelectAnimal();
        }
        public int getSelectIndex2(){
            return paneDisplay2.getSelectedIndex();
        }
        
        public String getSelectAnimal3(){
            return paneDisplay3.getSelectAnimal();
        }
        public int getSelectIndex3(){
            return paneDisplay3.getSelectedIndex();
        }
        public String getSelectAnimal4(){
            return paneDisplay4.getSelectAnimal();
        }
        public int getSelectIndex4(){
            return paneDisplay4.getSelectedIndex();
        }
        
        public void printSelect(){
            System.out.println(getAntal1());
            System.out.println(getSelectAnimal1());
            System.out.println(getSelectAnimal2());
        }
    void initialize()
    {
//        date.setText("Date: " + Dyreshop.getTime());
        System.out.println("Initialize "+receipt1);
        receipt1.initialize();
    }
    
    public void refresh()
    {
        receipt1.receitRefresh();
    }
public int selectedPane(){
    return Pane.getSelectedIndex();
}
    public void updateTotal(int a)
    {
        receipt1.setTotal(a);
    }






    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        shopName = new javax.swing.JLabel();
        Pane = new javax.swing.JTabbedPane();
        paneDisplay1 = new semesterprojekt.PaneDisplay();
        paneDisplay2 = new semesterprojekt.PaneDisplay();
        paneDisplay3 = new semesterprojekt.PaneDisplay();
        paneDisplay4 = new semesterprojekt.PaneDisplay();
        receipt1 = new semesterprojekt.Receipt();

        jButton1.setText("jButton1");

        jLabel1.setText("jLabel1");

        shopName.setText("Pet Shop");

        Pane.addTab("Aquatic", paneDisplay1);
        Pane.addTab("Reptile", paneDisplay2);
        Pane.addTab("Mammal", paneDisplay3);
        Pane.addTab("Bird", paneDisplay4);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(shopName)
                    .addComponent(receipt1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Pane, javax.swing.GroupLayout.Alignment.TRAILING)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(shopName)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Pane, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(receipt1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTabbedPane Pane;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private semesterprojekt.PaneDisplay paneDisplay1;
    private semesterprojekt.PaneDisplay paneDisplay2;
    private semesterprojekt.PaneDisplay paneDisplay3;
    private semesterprojekt.PaneDisplay paneDisplay4;
    private semesterprojekt.Receipt receipt1;
    private javax.swing.JLabel shopName;
    // End of variables declaration//GEN-END:variables
}


