/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package semesterprojekt;

import java.util.ArrayList;

/**
 *
 * @author Nicho
 */
public class Payment extends javax.swing.JPanel {

    Dyreshop dyreshop;
    GUI ejer;
    public static boolean payButton;
    public void initialize(Dyreshop dyreshop, GUI ejer)
    {
        this.dyreshop = dyreshop;
        this.ejer = ejer;
    }
    /**
     * Creates new form Payment
     */
    public Payment() {
        initComponents();        
    }

    public boolean getPayment ()
    {
        return payButton;
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        PaymentCard = new javax.swing.JButton();

        PaymentCard.setText("Credit Card");
        PaymentCard.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                PaymentCardStateChanged(evt);
            }
        });
        PaymentCard.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PaymentCardActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(131, 131, 131)
                .addComponent(PaymentCard)
                .addContainerGap(172, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(PaymentCard)
                .addContainerGap(262, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void PaymentCardActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PaymentCardActionPerformed
        dyreshop.resetBasket();
        ejer.updateBasket();
    }//GEN-LAST:event_PaymentCardActionPerformed

    private void PaymentCardStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_PaymentCardStateChanged
        // TODO add your handling code here:
    }//GEN-LAST:event_PaymentCardStateChanged


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton PaymentCard;
    // End of variables declaration//GEN-END:variables
}
